# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(270, 530, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 250, 47, 13))
        self.label_2.setObjectName("label_2")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(570, 530, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 160, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(270, 250, 381, 91))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(270, 430, 381, 91))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(186, 430, 71, 20))
        self.label_4.setObjectName("label_4")
        self.btn_encrypt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt_2.setGeometry(QtCore.QRect(760, 160, 111, 23))
        self.btn_encrypt_2.setObjectName("btn_encrypt_2")
        self.btn_encrypt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt_3.setGeometry(QtCore.QRect(830, 520, 75, 23))
        self.btn_encrypt_3.setObjectName("btn_encrypt_3")
        self.btn_decrypt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt_2.setGeometry(QtCore.QRect(1130, 520, 75, 23))
        self.btn_decrypt_2.setObjectName("btn_decrypt_2")
        self.txt_cipher_text_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text_2.setGeometry(QtCore.QRect(830, 420, 381, 91))
        self.txt_cipher_text_2.setObjectName("txt_cipher_text_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(750, 440, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(736, 240, 81, 20))
        self.label_3.setObjectName("label_3")
        self.txt_plain_text_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text_2.setGeometry(QtCore.QRect(830, 240, 381, 91))
        self.txt_plain_text_2.setObjectName("txt_plain_text_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.label_2.setText(_translate("MainWindow", "Plaintext"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_4.setText(_translate("MainWindow", "CipherText"))
        self.btn_encrypt_2.setText(_translate("MainWindow", "Generate Keys"))
        self.btn_encrypt_3.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt_2.setText(_translate("MainWindow", "Decrypt"))
        self.label_5.setText(_translate("MainWindow", "CipherText"))
        self.label_3.setText(_translate("MainWindow", "Information:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
